# Model-specific overrides for ucl.
model: ucl_bresnet
loader: class_incremental_loader

lr: 0.003
lr_rho: 0.001
beta: 0.001
alpha: 5
ratio: 0.1

eval_samples: 1 # Only used for epistemic uncertainty estimation
split: false
