#!/usr/bin/env python3
"""Read and summarize train-BWT CSV outputs.

Usage:
    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv

    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv \
        --details-csv analysis/train_bwt_full_til_details.csv \
        --algos "rwalk,icarl"
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Sequence


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments for CSV-based train-BWT reporting."""
    parser = argparse.ArgumentParser(
        description="Read and summarize train-BWT CSV outputs."
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        required=True,
        help="Path to summary CSV generated by compute_train_bwt.py (--csv).",
    )
    parser.add_argument(
        "--details-csv",
        type=Path,
        default=None,
        help="Optional details CSV generated by compute_train_bwt.py (--details-csv).",
    )
    parser.add_argument(
        "--algos",
        type=str,
        default=None,
        help=(
            "Optional comma-separated algorithm subset to keep (for example "
            "'rwalk,icarl')."
        ),
    )
    return parser.parse_args()


def _parse_algo_subset(algos_arg: str | None) -> set[str] | None:
    """Parse a comma-separated algorithm list into a normalized subset."""
    if algos_arg is None:
        return None
    parsed = {token.strip().lower() for token in algos_arg.split(",") if token.strip()}
    if not parsed:
        raise SystemExit("--algos was provided but no algorithm names were parsed.")
    return parsed


def _read_csv_rows(csv_path: Path) -> List[Dict[str, str]]:
    """Load rows from a CSV file into a list of dict records."""
    if not csv_path.is_file():
        raise SystemExit(f"CSV file does not exist: {csv_path}")
    with csv_path.open("r", encoding="utf-8", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        return list(reader)


def _filter_by_algorithms(
    rows: Sequence[Dict[str, str]], selected_algorithms: set[str] | None
) -> List[Dict[str, str]]:
    """Filter CSV records by algorithm subset."""
    if selected_algorithms is None:
        return list(rows)
    return [
        row
        for row in rows
        if row.get("algo", "").strip().lower() in selected_algorithms
    ]


def _print_summary_table(rows: Sequence[Dict[str, str]]) -> None:
    """Print compact summary rows for train-BWT results."""
    if not rows:
        print("No summary rows to display.")
        return
    sorted_rows = sorted(rows, key=lambda row: row.get("algo", ""))
    print(f"{'algo':<14} {'tasks':>5} {'avg_forgetting':>14} {'train_bwt_proxy':>16}")
    print("-" * 55)
    for row in sorted_rows:
        algo_name = row.get("algo", "unknown")
        task_count = int(float(row.get("n_tasks", "0")))
        avg_forgetting = float(row.get("avg_forgetting_0_to_t_minus_2", "nan"))
        train_bwt_proxy = float(row.get("train_bwt_proxy", "nan"))
        print(
            f"{algo_name:<14} {task_count:5d} {avg_forgetting:14.6f} "
            f"{train_bwt_proxy:16.6f}"
        )


def _print_details_stats(rows: Sequence[Dict[str, str]]) -> None:
    """Print a compact per-algorithm count of detail rows."""
    if not rows:
        print("No detail rows to display.")
        return
    counts_by_algo: Dict[str, int] = {}
    for row in rows:
        algo_name = row.get("algo", "unknown")
        counts_by_algo[algo_name] = counts_by_algo.get(algo_name, 0) + 1
    print("\nPer-algorithm detail rows:")
    for algo_name in sorted(counts_by_algo):
        print(f"- {algo_name}: {counts_by_algo[algo_name]}")


def main() -> None:
    """Run CSV summary reporting for previously computed train-BWT outputs."""
    args = _parse_args()
    selected_algorithms = _parse_algo_subset(args.algos)

    summary_rows = _read_csv_rows(args.summary_csv)
    summary_rows = _filter_by_algorithms(summary_rows, selected_algorithms)
    print(f"Loaded summary rows: {len(summary_rows)}")
    _print_summary_table(summary_rows)

    if args.details_csv is not None:
        detail_rows = _read_csv_rows(args.details_csv)
        detail_rows = _filter_by_algorithms(detail_rows, selected_algorithms)
        print(f"\nLoaded detail rows: {len(detail_rows)}")
        _print_details_stats(detail_rows)


if __name__ == "__main__":
    main()
