#!/usr/bin/env python3
"""Read and summarize train-BWT CSV outputs.

Usage:
    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv

    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv \
        --details-csv analysis/train_bwt_full_til_details.csv \
        --algos "rwalk,icarl"
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Dict, List, Sequence


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments for CSV-based train-BWT reporting."""
    parser = argparse.ArgumentParser(
        description="Read and summarize train-BWT CSV outputs."
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        required=True,
        help="Path to summary CSV generated by compute_train_bwt.py (--csv).",
    )
    parser.add_argument(
        "--details-csv",
        type=Path,
        default=None,
        help="Optional details CSV generated by compute_train_bwt.py (--details-csv).",
    )
    parser.add_argument(
        "--algos",
        type=str,
        default=None,
        help=(
            "Optional comma-separated algorithm subset to keep (for example "
            "'rwalk,icarl')."
        ),
    )
    parser.add_argument(
        "--markdown",
        action="store_true",
        help="Print summary table in Markdown format (without tasks column).",
    )
    return parser.parse_args()


def _parse_algo_subset(algos_arg: str | None) -> set[str] | None:
    """Parse a comma-separated algorithm list into a normalized subset."""
    if algos_arg is None:
        return None
    parsed = {token.strip().lower() for token in algos_arg.split(",") if token.strip()}
    if not parsed:
        raise SystemExit("--algos was provided but no algorithm names were parsed.")
    return parsed


def _read_csv_rows(csv_path: Path) -> List[Dict[str, str]]:
    """Load rows from a CSV file into a list of dict records."""
    if not csv_path.is_file():
        raise SystemExit(f"CSV file does not exist: {csv_path}")
    with csv_path.open("r", encoding="utf-8", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        return list(reader)


def _filter_by_algorithms(
    rows: Sequence[Dict[str, str]], selected_algorithms: set[str] | None
) -> List[Dict[str, str]]:
    """Filter CSV records by algorithm subset."""
    if selected_algorithms is None:
        return list(rows)
    return [
        row
        for row in rows
        if row.get("algo", "").strip().lower() in selected_algorithms
    ]


def _get_avg_forgetting_value(summary_row: Dict[str, str]) -> float:
    """Return avg forgetting from either legacy or current summary schema."""
    if "avg_representational_forgetting_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_representational_forgetting_0_to_t_minus_2"])
    return float(summary_row.get("avg_forgetting_0_to_t_minus_2", "nan"))


def _get_avg_test_forgetting_value(summary_row: Dict[str, str]) -> float:
    """Return avg test forgetting from either legacy or current schema."""
    if "avg_test_forgetting_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_test_forgetting_0_to_t_minus_2"])
    return float(summary_row.get("avg_tf", "nan"))


def _get_avg_generalisation_shift_value(summary_row: Dict[str, str]) -> float:
    """Return avg generalisation shift from either legacy or current schema."""
    if "avg_generalisation_shift_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_generalisation_shift_0_to_t_minus_2"])
    return float(summary_row.get("avg_gs", "nan"))


def _get_first_float_from_row(detail_row: Dict[str, str], keys: Sequence[str]) -> float:
    """Return first parseable float value among candidate keys, else NaN."""
    for key in keys:
        raw_value = detail_row.get(key)
        if raw_value is None or raw_value == "":
            continue
        try:
            return float(raw_value)
        except ValueError:
            continue
    return float("nan")


def _resolve_representational_forgetting(detail_row: Dict[str, str]) -> float:
    """Resolve representational forgetting across legacy/current schemas."""
    direct_value = _get_first_float_from_row(
        detail_row, ("representational_forgetting", "avg_forgetting", "forgetting")
    )
    if not math.isnan(direct_value):
        return direct_value
    train_after_task_value = _get_first_float_from_row(
        detail_row, ("train_f1_after_task", "train_f1_peak")
    )
    final_train_value = _get_first_float_from_row(
        detail_row, ("final_train_f1", "train_f1_final")
    )
    if math.isnan(train_after_task_value) or math.isnan(final_train_value):
        return float("nan")
    return train_after_task_value - final_train_value


def _print_summary_table(rows: Sequence[Dict[str, str]], markdown: bool = False) -> None:
    """Print compact summary rows for train-BWT results."""
    if not rows:
        print("No summary rows to display.")
        return
    sorted_rows = sorted(rows, key=lambda row: row.get("algo", ""))
    if markdown:
        print("| algo | avg_rf | avg_tf | avg_gs | train_bwt |")
        print("| --- | ---: | ---: | ---: | ---: |")
        for row in sorted_rows:
            algo_name = row.get("algo", "unknown")
            avg_forgetting = _get_avg_forgetting_value(row)
            avg_test_forgetting = _get_avg_test_forgetting_value(row)
            avg_generalisation_shift = _get_avg_generalisation_shift_value(row)
            train_bwt_proxy = float(row.get("train_bwt_proxy", "nan"))
            print(
                f"| {algo_name} | {avg_forgetting:.6f} | {avg_test_forgetting:.6f} | "
                f"{avg_generalisation_shift:.6f} | {train_bwt_proxy:.6f} |"
            )
        return

    print(
        f"{'algo':<14} {'tasks':>5} {'avg_rf':>12} {'avg_tf':>12} {'avg_gs':>12} "
        f"{'train_bwt':>12}"
    )
    print("-" * 74)
    for row in sorted_rows:
        algo_name = row.get("algo", "unknown")
        task_count = int(float(row.get("n_tasks", "0")))
        avg_forgetting = _get_avg_forgetting_value(row)
        avg_test_forgetting = _get_avg_test_forgetting_value(row)
        avg_generalisation_shift = _get_avg_generalisation_shift_value(row)
        train_bwt_proxy = float(row.get("train_bwt_proxy", "nan"))
        print(
            f"{algo_name:<14} {task_count:5d} {avg_forgetting:12.6f} "
            f"{avg_test_forgetting:12.6f} {avg_generalisation_shift:12.6f} "
            f"{train_bwt_proxy:12.6f}"
        )


def _print_details_stats(rows: Sequence[Dict[str, str]]) -> None:
    """Print detail-row counts and forgetting coverage by algorithm."""
    if not rows:
        print("No detail rows to display.")
        return
    counts_by_algo: Dict[str, int] = {}
    valid_forgetting_counts_by_algo: Dict[str, int] = {}
    forgetting_sum_by_algo: Dict[str, float] = {}
    for row in rows:
        algo_name = row.get("algo", "unknown")
        counts_by_algo[algo_name] = counts_by_algo.get(algo_name, 0) + 1
        representational_forgetting = _resolve_representational_forgetting(row)
        if math.isnan(representational_forgetting):
            continue
        valid_forgetting_counts_by_algo[algo_name] = (
            valid_forgetting_counts_by_algo.get(algo_name, 0) + 1
        )
        forgetting_sum_by_algo[algo_name] = (
            forgetting_sum_by_algo.get(algo_name, 0.0) + representational_forgetting
        )
    print(
        "\nPer-algorithm detail rows "
        "(valid_rf_rows and mean_rf include legacy/current schemas):"
    )
    for algo_name in sorted(counts_by_algo):
        total_row_count = counts_by_algo[algo_name]
        valid_row_count = valid_forgetting_counts_by_algo.get(algo_name, 0)
        mean_forgetting = (
            forgetting_sum_by_algo[algo_name] / valid_row_count
            if valid_row_count > 0
            else float("nan")
        )
        print(
            f"- {algo_name}: total_rows={total_row_count}, "
            f"valid_rf_rows={valid_row_count}, mean_rf={mean_forgetting:.6f}"
        )


def main() -> None:
    """Run CSV summary reporting for previously computed train-BWT outputs."""
    args = _parse_args()
    selected_algorithms = _parse_algo_subset(args.algos)

    summary_rows = _read_csv_rows(args.summary_csv)
    summary_rows = _filter_by_algorithms(summary_rows, selected_algorithms)
    print(f"Loaded summary rows: {len(summary_rows)}")
    _print_summary_table(summary_rows, markdown=args.markdown)

    if args.details_csv is not None:
        detail_rows = _read_csv_rows(args.details_csv)
        detail_rows = _filter_by_algorithms(detail_rows, selected_algorithms)
        print(f"\nLoaded detail rows: {len(detail_rows)}")
        _print_details_stats(detail_rows)


if __name__ == "__main__":
    main()
