#!/usr/bin/env python3
"""Read and summarize train-BWT CSV outputs.

Usage:
    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv

    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_summary.csv \
        --details-csv analysis/train_bwt_full_til_details.csv \
        --algos "rwalk,icarl"

    # Details-only (same columns as --details-csv output): auto-aggregated.
    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_details.csv \
        --show-per-task

    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_details.csv \
        --plot-tf-per-task analysis/tf_per_task.png

    # Single curve: mean tf at each task, averaged over algorithms (same PNG flag).
    python scripts/read_train_bwt_csv.py \
        --summary-csv analysis/train_bwt_full_til_details.csv \
        --plot-tf-per-task analysis/tf_mean.png --plot-tf-mean-across-algos
"""

from __future__ import annotations

import argparse
import csv
import math
import statistics
from collections import defaultdict
from pathlib import Path
from typing import DefaultDict, Dict, List, Sequence, Tuple


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments for CSV-based train-BWT reporting."""
    parser = argparse.ArgumentParser(
        description="Read and summarize train-BWT CSV outputs."
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        required=True,
        help=(
            "Path to summary CSV from compute_train_bwt.py (--csv), or a "
            "per-task details CSV (--details-csv output); the latter is "
            "auto-detected and aggregated to one row per run."
        ),
    )
    parser.add_argument(
        "--details-csv",
        type=Path,
        default=None,
        help="Optional details CSV generated by compute_train_bwt.py (--details-csv).",
    )
    parser.add_argument(
        "--algos",
        type=str,
        default=None,
        help=(
            "Optional comma-separated algorithm subset to keep (for example "
            "'rwalk,icarl')."
        ),
    )
    parser.add_argument(
        "--show-per-task",
        action="store_true",
        help=(
            "After the summary table, print one line per task (rf, tf, gs, "
            "train/test F1 peaks and finals) when detail rows are available "
            "(--details-csv or a details-only --summary-csv)."
        ),
    )
    parser.add_argument(
        "--plot-tf-per-task",
        type=Path,
        default=None,
        metavar="PNG",
        help=(
            "Save a line plot of per-task test forgetting (tf) vs task index "
            "(detail rows required). Default: one curve per algorithm. With "
            "--plot-tf-mean-across-algos, plot a single curve: at each task, "
            "mean tf over algorithms (each algo contributes at most one value "
            "per task after intra-run averaging). If several runs share the "
            "same algo and task, tf is averaged first within that algo."
        ),
    )
    parser.add_argument(
        "--plot-tf-mean-across-algos",
        action="store_true",
        help=(
            "Use with --plot-tf-per-task: draw only the across-algorithm mean "
            "of tf at each task index instead of one line per algorithm."
        ),
    )
    return parser.parse_args()


def _parse_algo_subset(algos_arg: str | None) -> set[str] | None:
    """Parse a comma-separated algorithm list into a normalized subset."""
    if algos_arg is None:
        return None
    parsed = {token.strip().lower() for token in algos_arg.split(",") if token.strip()}
    if not parsed:
        raise SystemExit("--algos was provided but no algorithm names were parsed.")
    return parsed


def _read_csv_with_headers(csv_path: Path) -> Tuple[List[str], List[Dict[str, str]]]:
    """Load header names and rows from a CSV file."""
    if not csv_path.is_file():
        raise SystemExit(f"CSV file does not exist: {csv_path}")
    with csv_path.open("r", encoding="utf-8", newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        fieldnames = list(reader.fieldnames or [])
        return fieldnames, list(reader)


def _read_csv_rows(csv_path: Path) -> List[Dict[str, str]]:
    """Load rows from a CSV file into a list of dict records."""
    _fieldnames, rows = _read_csv_with_headers(csv_path)
    return rows


def _is_per_task_train_bwt_details_csv(fieldnames: Sequence[str]) -> bool:
    """Return True when CSV matches compute_train_bwt.py --details-csv schema."""
    names = {name.strip() for name in fieldnames if name}
    return (
        "task" in names
        and "representational_forgetting" in names
        and "n_tasks" not in names
    )


def _aggregate_per_task_rows_to_summary(
    detail_rows: Sequence[Dict[str, str]],
) -> List[Dict[str, str]]:
    """Build run-level summary rows from per-task detail rows.

    Averages match ``compute_train_bwt._rows_and_aggregate``: means are taken
    over tasks ``0 .. T-2`` (all completed tasks except the last) for
    representational forgetting, test forgetting, and generalisation shift;
    ``f1_total_*`` are means of final train/test F1 over all tasks.

    Args:
        detail_rows: Records from a details CSV.

    Returns:
        One string-valued dict per distinct ``(algo, job_log, run_dir)`` group.

    Usage:
        Invoked from :func:`main` when ``--summary-csv`` is a details file; not
        usually called directly.
    """
    groups: Dict[Tuple[str, str, str], List[Dict[str, str]]] = defaultdict(list)
    for row in detail_rows:
        key = (
            row.get("algo", "").strip(),
            row.get("job_log", "").strip(),
            row.get("run_dir", "").strip(),
        )
        groups[key].append(row)

    summary_rows: List[Dict[str, str]] = []
    for (_algo, _job, _run), group_rows in groups.items():
        if not group_rows:
            continue
        sorted_rows = sorted(
            group_rows,
            key=lambda record: int(float(record.get("task", "0"))),
        )
        task_count = len(sorted_rows)
        if task_count < 2:
            avg_rf = float("nan")
            avg_tf = float("nan")
            avg_gs = float("nan")
        else:
            prefix_rows = sorted_rows[:-1]
            avg_rf = statistics.mean(
                float(r["representational_forgetting"]) for r in prefix_rows
            )
            avg_tf = statistics.mean(float(r["test_forgetting"]) for r in prefix_rows)
            avg_gs = statistics.mean(
                float(r["generalisation_shift"]) for r in prefix_rows
            )
        f1_total_tr = statistics.mean(float(r["final_train_f1"]) for r in sorted_rows)
        f1_total_te = statistics.mean(float(r["final_test_f1"]) for r in sorted_rows)
        train_bwt_proxy = -avg_rf if not math.isnan(avg_rf) else float("nan")
        first = sorted_rows[0]
        summary_rows.append(
            {
                "algo": first.get("algo", ""),
                "job_log": first.get("job_log", ""),
                "run_dir": first.get("run_dir", ""),
                "n_tasks": str(task_count),
                "avg_representational_forgetting_0_to_t_minus_2": str(avg_rf),
                "avg_test_forgetting_0_to_t_minus_2": str(avg_tf),
                "avg_generalisation_shift_0_to_t_minus_2": str(avg_gs),
                "f1_total_tr": str(f1_total_tr),
                "f1_total_te": str(f1_total_te),
                "train_bwt_proxy": str(train_bwt_proxy),
            }
        )
    return summary_rows


def _filter_by_algorithms(
    rows: Sequence[Dict[str, str]], selected_algorithms: set[str] | None
) -> List[Dict[str, str]]:
    """Filter CSV records by algorithm subset."""
    if selected_algorithms is None:
        return list(rows)
    return [
        row
        for row in rows
        if row.get("algo", "").strip().lower() in selected_algorithms
    ]


def _get_avg_forgetting_value(summary_row: Dict[str, str]) -> float:
    """Return avg forgetting from either legacy or current summary schema."""
    if "avg_representational_forgetting_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_representational_forgetting_0_to_t_minus_2"])
    return float(summary_row.get("avg_forgetting_0_to_t_minus_2", "nan"))


def _get_avg_test_forgetting_value(summary_row: Dict[str, str]) -> float:
    """Return avg test forgetting from either legacy or current schema."""
    if "avg_test_forgetting_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_test_forgetting_0_to_t_minus_2"])
    return float(summary_row.get("avg_tf", "nan"))


def _get_avg_generalisation_shift_value(summary_row: Dict[str, str]) -> float:
    """Return avg generalisation shift from either legacy or current schema."""
    if "avg_generalisation_shift_0_to_t_minus_2" in summary_row:
        return float(summary_row["avg_generalisation_shift_0_to_t_minus_2"])
    return float(summary_row.get("avg_gs", "nan"))


def _get_tr_f1_value(summary_row: Dict[str, str]) -> float:
    """Return mean final train cls_f1 (``f1_total_tr``) when present.

    Args:
        summary_row: One record from a ``compute_train_bwt.py`` summary CSV.

    Returns:
        Parsed float, or NaN when the column is missing or empty.

    Usage:
        >>> _get_tr_f1_value({"f1_total_tr": "0.5"})
        0.5
    """
    return _get_first_float_from_row(summary_row, ("f1_total_tr", "tr_f1"))


def _get_te_f1_value(summary_row: Dict[str, str]) -> float:
    """Return mean final test cls_f1 (``f1_total_te``) when present.

    Args:
        summary_row: One record from a ``compute_train_bwt.py`` summary CSV.

    Returns:
        Parsed float, or NaN when the column is missing or empty.

    Usage:
        >>> _get_te_f1_value({"f1_total_te": "0.4"})
        0.4
    """
    return _get_first_float_from_row(summary_row, ("f1_total_te", "te_f1"))


def _get_first_float_from_row(detail_row: Dict[str, str], keys: Sequence[str]) -> float:
    """Return first parseable float value among candidate keys, else NaN."""
    for key in keys:
        raw_value = detail_row.get(key)
        if raw_value is None or raw_value == "":
            continue
        try:
            return float(raw_value)
        except ValueError:
            continue
    return float("nan")


def _resolve_representational_forgetting(detail_row: Dict[str, str]) -> float:
    """Resolve representational forgetting across legacy/current schemas."""
    direct_value = _get_first_float_from_row(
        detail_row, ("representational_forgetting", "avg_forgetting", "forgetting")
    )
    if not math.isnan(direct_value):
        return direct_value
    train_after_task_value = _get_first_float_from_row(
        detail_row, ("train_f1_after_task", "train_f1_peak")
    )
    final_train_value = _get_first_float_from_row(
        detail_row, ("final_train_f1", "train_f1_final")
    )
    if math.isnan(train_after_task_value) or math.isnan(final_train_value):
        return float("nan")
    return train_after_task_value - final_train_value


def _print_summary_table(rows: Sequence[Dict[str, str]]) -> None:
    """Print compact summary rows for train-BWT results."""
    if not rows:
        print("No summary rows to display.")
        return
    sorted_rows = sorted(rows, key=lambda row: row.get("algo", ""))
    print(
        f"{'algo':<14} {'tasks':>5} {'avg_rf':>12} {'avg_tf':>12} {'avg_gs':>12} "
        f"{'tr_f1':>10} {'te_f1':>10} {'train_bwt':>12}"
    )
    print("-" * 96)
    for row in sorted_rows:
        algo_name = row.get("algo", "unknown")
        task_count = int(float(row.get("n_tasks", "0")))
        avg_forgetting = _get_avg_forgetting_value(row)
        avg_test_forgetting = _get_avg_test_forgetting_value(row)
        avg_generalisation_shift = _get_avg_generalisation_shift_value(row)
        tr_f1 = _get_tr_f1_value(row)
        te_f1 = _get_te_f1_value(row)
        train_bwt_proxy = float(row.get("train_bwt_proxy", "nan"))
        print(
            f"{algo_name:<14} {task_count:5d} {avg_forgetting:12.6f} "
            f"{avg_test_forgetting:12.6f} {avg_generalisation_shift:12.6f} "
            f"{tr_f1:10.6f} {te_f1:10.6f} {train_bwt_proxy:12.6f}"
        )


def _collect_test_forgetting_by_algo_and_task(
    detail_rows: Sequence[Dict[str, str]],
) -> Dict[str, Dict[int, float]]:
    """Aggregate per-task test forgetting, keyed by algorithm then task index.

    When multiple detail rows share the same ``(algo, task)`` (different
    ``job_log`` / ``run_dir``), forgetting values are averaged with
    :func:`statistics.mean`.

    Args:
        detail_rows: Records from a train-BWT details CSV.

    Returns:
        Mapping ``algo_name -> {task_index -> mean_tf}``.

    Usage:
        Used by :func:`_plot_test_forgetting_per_task`; not typically called
        directly from the shell.
    """
    buckets: DefaultDict[str, DefaultDict[int, List[float]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for record in detail_rows:
        algo_name = record.get("algo", "").strip()
        if not algo_name:
            continue
        task_index = int(float(record.get("task", "0")))
        tf_value = _get_first_float_from_row(record, ("test_forgetting",))
        if math.isnan(tf_value):
            continue
        buckets[algo_name][task_index].append(tf_value)
    aggregated: Dict[str, Dict[int, float]] = {}
    for algo_name, task_map in buckets.items():
        aggregated[algo_name] = {
            task_index: float(statistics.mean(values))
            for task_index, values in sorted(task_map.items())
        }
    return aggregated


def _per_task_mean_tf_across_algorithms(
    tf_by_algo: Dict[str, Dict[int, float]],
) -> Dict[int, float]:
    """For each task index, average ``tf`` over all algorithms that define it.

    Args:
        tf_by_algo: Mapping ``algo -> {task -> tf}`` as produced by
            :func:`_collect_test_forgetting_by_algo_and_task`.

    Returns:
        Sorted-by-task mapping ``task_index -> mean_tf``.

    Usage:
        Used when plotting with ``--plot-tf-mean-across-algos``.
    """
    by_task: DefaultDict[int, List[float]] = defaultdict(list)
    for _algo_name, task_map in tf_by_algo.items():
        for task_index, tf_value in task_map.items():
            by_task[task_index].append(tf_value)
    return {
        task_index: float(statistics.mean(values))
        for task_index, values in sorted(by_task.items())
    }


def _plot_test_forgetting_per_task(
    tf_by_algo: Dict[str, Dict[int, float]],
    output_path: Path,
    *,
    mean_across_algorithms: bool,
) -> None:
    """Save a line chart of test forgetting vs task index.

    Args:
        tf_by_algo: From :func:`_collect_test_forgetting_by_algo_and_task`.
        output_path: PNG path (parent directories are created if missing).
        mean_across_algorithms: If True, one series (mean tf over algos per task).
            If False, one series per algorithm.

    Usage:
        Invoked from the CLI with ``--plot-tf-per-task path/to/out.png`` and
        optionally ``--plot-tf-mean-across-algos``.
    """
    import matplotlib.pyplot as plt

    if not tf_by_algo:
        raise SystemExit("No test-forgetting values to plot.")
    figure, axes = plt.subplots(figsize=(10, 5))
    if mean_across_algorithms:
        mean_by_task = _per_task_mean_tf_across_algorithms(tf_by_algo)
        if not mean_by_task:
            raise SystemExit("No test-forgetting values to plot (mean curve).")
        task_indices = sorted(mean_by_task.keys())
        tf_values = [mean_by_task[task_index] for task_index in task_indices]
        axes.plot(
            task_indices,
            tf_values,
            marker="o",
            markersize=4,
            linewidth=2.0,
            color="C0",
            label="Mean across algorithms",
        )
        axes.set_title("Mean per-task test forgetting (across algorithms)")
        axes.legend(loc="best", fontsize=9)
    else:
        for algo_name in sorted(tf_by_algo.keys(), key=str.lower):
            task_map = tf_by_algo[algo_name]
            task_indices = sorted(task_map.keys())
            series_values = [task_map[task_index] for task_index in task_indices]
            axes.plot(
                task_indices,
                series_values,
                marker="o",
                markersize=3,
                linewidth=1.5,
                label=algo_name,
            )
        axes.set_title("Per-task test forgetting by algorithm")
        axes.legend(
            bbox_to_anchor=(1.02, 1.0),
            loc="upper left",
            fontsize=7,
            ncol=1,
        )
    axes.set_xlabel("Task index")
    axes.set_ylabel("Test forgetting (tf)")
    axes.grid(True, alpha=0.3)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(figure)
    suffix = " (mean across algorithms)" if mean_across_algorithms else ""
    print(f"Wrote tf-per-task plot{suffix}: {output_path.resolve()}")


def _print_per_task_metrics(rows: Sequence[Dict[str, str]]) -> None:
    """Print one row per task with forgetting and F1 columns from a details CSV."""
    if not rows:
        return
    ordered = sorted(
        rows,
        key=lambda record: (
            record.get("algo", "").lower(),
            int(float(record.get("task", "0"))),
        ),
    )
    print("\nPer-task metrics (details rows):")
    header = (
        f"{'algo':<12} {'task':>4} {'rf':>10} {'tf':>10} {'gs':>10} "
        f"{'tr_peak':>9} {'fin_tr':>9} {'fin_te':>9}"
    )
    print(header)
    print("-" * min(100, len(header)))
    for record in ordered:
        algo_name = record.get("algo", "")[:12]
        task_index = int(float(record.get("task", "0")))
        rf = _resolve_representational_forgetting(record)
        tf = _get_first_float_from_row(record, ("test_forgetting",))
        gs = _get_first_float_from_row(record, ("generalisation_shift",))
        tr_peak = _get_first_float_from_row(
            record, ("train_f1_after_task", "train_f1_peak")
        )
        fin_tr = _get_first_float_from_row(record, ("final_train_f1",))
        fin_te = _get_first_float_from_row(record, ("final_test_f1",))
        print(
            f"{algo_name:<12} {task_index:4d} "
            f"{rf:10.6f} {tf:10.6f} {gs:10.6f} "
            f"{tr_peak:9.4f} {fin_tr:9.4f} {fin_te:9.4f}"
        )


def _print_details_stats(rows: Sequence[Dict[str, str]]) -> None:
    """Print detail-row counts and mean RF over **all** tasks (including last).

    The printed ``mean_rf`` is the arithmetic mean of per-task representational
    forgetting across every detail row for that algorithm. It therefore
    differs from the summary table's ``avg_rf``, which averages only tasks
    ``0 .. T-2`` to match ``compute_train_bwt.py``.
    """
    if not rows:
        print("No detail rows to display.")
        return
    counts_by_algo: Dict[str, int] = {}
    valid_forgetting_counts_by_algo: Dict[str, int] = {}
    forgetting_sum_by_algo: Dict[str, float] = {}
    for row in rows:
        algo_name = row.get("algo", "unknown")
        counts_by_algo[algo_name] = counts_by_algo.get(algo_name, 0) + 1
        representational_forgetting = _resolve_representational_forgetting(row)
        if math.isnan(representational_forgetting):
            continue
        valid_forgetting_counts_by_algo[algo_name] = (
            valid_forgetting_counts_by_algo.get(algo_name, 0) + 1
        )
        forgetting_sum_by_algo[algo_name] = (
            forgetting_sum_by_algo.get(algo_name, 0.0) + representational_forgetting
        )
    print(
        "\nPer-algorithm detail rows "
        "(valid_rf_rows and mean_rf include legacy/current schemas):"
    )
    for algo_name in sorted(counts_by_algo):
        total_row_count = counts_by_algo[algo_name]
        valid_row_count = valid_forgetting_counts_by_algo.get(algo_name, 0)
        mean_forgetting = (
            forgetting_sum_by_algo[algo_name] / valid_row_count
            if valid_row_count > 0
            else float("nan")
        )
        print(
            f"- {algo_name}: total_rows={total_row_count}, "
            f"valid_rf_rows={valid_row_count}, mean_rf={mean_forgetting:.6f}"
        )


def main() -> None:
    """Run CSV summary reporting for previously computed train-BWT outputs."""
    args = _parse_args()
    selected_algorithms = _parse_algo_subset(args.algos)

    summary_fieldnames, raw_summary_rows = _read_csv_with_headers(args.summary_csv)
    raw_summary_rows = _filter_by_algorithms(raw_summary_rows, selected_algorithms)
    auto_detail_rows: List[Dict[str, str]] | None = None
    if _is_per_task_train_bwt_details_csv(summary_fieldnames):
        print(
            "Note: --summary-csv is a per-task details file; aggregating one "
            "summary row per (algo, job_log, run_dir) using the same averages "
            "as compute_train_bwt.py (rf/tf/gs over tasks 0..T-2). "
            "Per-task columns are unchanged in the CSV; use --show-per-task to "
            "print them here."
        )
        summary_rows = _aggregate_per_task_rows_to_summary(raw_summary_rows)
        auto_detail_rows = raw_summary_rows
    else:
        summary_rows = raw_summary_rows

    print(f"Loaded summary rows: {len(summary_rows)}")
    _print_summary_table(summary_rows)

    detail_rows_for_display: List[Dict[str, str]] | None = None
    if args.details_csv is not None:
        _detail_fieldnames, detail_rows = _read_csv_with_headers(args.details_csv)
        del _detail_fieldnames
        detail_rows = _filter_by_algorithms(detail_rows, selected_algorithms)
        detail_rows_for_display = detail_rows
        print(f"\nLoaded detail rows: {len(detail_rows)}")
        _print_details_stats(detail_rows)
    elif auto_detail_rows is not None:
        detail_rows_for_display = auto_detail_rows
        print(f"\nLoaded detail rows: {len(auto_detail_rows)}")
        _print_details_stats(auto_detail_rows)

    if args.show_per_task and detail_rows_for_display:
        _print_per_task_metrics(detail_rows_for_display)
    elif args.show_per_task and detail_rows_for_display is None:
        print(
            "\n[WARN] --show-per-task ignored: no detail rows loaded "
            "(use --details-csv or a details-only --summary-csv).",
            flush=True,
        )

    if args.plot_tf_mean_across_algos and args.plot_tf_per_task is None:
        raise SystemExit(
            "--plot-tf-mean-across-algos requires --plot-tf-per-task PNG path."
        )

    if args.plot_tf_per_task is not None:
        if detail_rows_for_display:
            tf_series = _collect_test_forgetting_by_algo_and_task(
                detail_rows_for_display
            )
            _plot_test_forgetting_per_task(
                tf_series,
                args.plot_tf_per_task,
                mean_across_algorithms=bool(args.plot_tf_mean_across_algos),
            )
        else:
            print(
                "\n[WARN] --plot-tf-per-task ignored: no detail rows loaded "
                "(use --details-csv or a details-only --summary-csv).",
                flush=True,
            )


if __name__ == "__main__":
    main()
