# Model-specific overrides for ucl.
model: ucl_bresnet
loader: task_incremental_loader

lr: 0.01
lr_rho: 0.001
beta: 0.02
alpha: 0.1
ratio: 0.001

eval_samples: 1 # Only used for epistemic uncertainty estimation
split: true
